name: MPS-CLI-TYPESCRIPT_CI

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.MPSCLI_GITHUB_PKG_REGISTRY }}

jobs:
  build_mps_cli_py:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test